# Generated by Django 5.0 on 2023-12-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='extended_props',
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project5.project'),
            preserve_default=False,
        ),
    ]
