# Generated by Django 5.0 on 2023-12-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project5', '0002_remove_event_extended_props_event_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
